/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContributorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const ContributorRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : ContributorStatus,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContributorRequests' : IDL.Func(
      [],
      [IDL.Vec(ContributorRequest)],
      ['query'],
    ),
  'getApprovedContributors' : IDL.Func(
      [],
      [IDL.Vec(ContributorRequest)],
      ['query'],
    ),
  'getPendingContributorRequests' : IDL.Func(
      [],
      [IDL.Vec(ContributorRequest)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'submitContributorRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateContributorStatus' : IDL.Func([IDL.Nat, ContributorStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContributorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContributorRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : ContributorStatus,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContributorRequests' : IDL.Func(
        [],
        [IDL.Vec(ContributorRequest)],
        ['query'],
      ),
    'getApprovedContributors' : IDL.Func(
        [],
        [IDL.Vec(ContributorRequest)],
        ['query'],
      ),
    'getPendingContributorRequests' : IDL.Func(
        [],
        [IDL.Vec(ContributorRequest)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'submitContributorRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateContributorStatus' : IDL.Func([IDL.Nat, ContributorStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };