/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContributorRequest {
    id: bigint;
    status: ContributorStatus;
    subject: string;
    name: string;
    createdAt: Time;
    description: string;
    email: string;
}
export type Time = bigint;
export enum ContributorStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    getAllContributorRequests(): Promise<Array<ContributorRequest>>;
    getApprovedContributors(): Promise<Array<ContributorRequest>>;
    getPendingContributorRequests(): Promise<Array<ContributorRequest>>;
    seedData(): Promise<void>;
    submitContributorRequest(name: string, email: string, subject: string, description: string): Promise<bigint>;
    updateContributorStatus(id: bigint, status: ContributorStatus): Promise<void>;
}
import type { ContributorRequest as _ContributorRequest, ContributorStatus as _ContributorStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllContributorRequests(): Promise<Array<ContributorRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContributorRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContributorRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedContributors(): Promise<Array<ContributorRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedContributors();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedContributors();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingContributorRequests(): Promise<Array<ContributorRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingContributorRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingContributorRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async submitContributorRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContributorRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContributorRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateContributorStatus(arg0: bigint, arg1: ContributorStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContributorStatus(arg0, to_candid_ContributorStatus_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContributorStatus(arg0, to_candid_ContributorStatus_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ContributorRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributorRequest): ContributorRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ContributorStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributorStatus): ContributorStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ContributorStatus;
    subject: string;
    name: string;
    createdAt: _Time;
    description: string;
    email: string;
}): {
    id: bigint;
    status: ContributorStatus;
    subject: string;
    name: string;
    createdAt: Time;
    description: string;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_ContributorStatus_n4(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        email: value.email
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ContributorStatus {
    return "pending" in value ? ContributorStatus.pending : "approved" in value ? ContributorStatus.approved : "rejected" in value ? ContributorStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContributorRequest>): Array<ContributorRequest> {
    return value.map((x)=>from_candid_ContributorRequest_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ContributorStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributorStatus): _ContributorStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributorStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ContributorStatus.pending ? {
        pending: null
    } : value == ContributorStatus.approved ? {
        approved: null
    } : value == ContributorStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
